### ISSUE TITLE
pry isn't working in this lab.

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/oo-email-parser#12]
bundle install and gem install pry doesn't work in terminal because it says cannot locate gemfile.

**Comment by morgvanny** [comment]
bundle install won't work because, like you said, there's no gemfile. gem install pry should still work, and ensure that pry is installed globally. If you do that, and then put require 'pry' at the top of the file, binding.pry should then work. If not, go ahead and use Ask A Question and we'll see what we can do to help!
